import type { FitnessErrorCode } from '@/features/fitness-tracker/domain/errors';

export const fitnessStrings = {
  common: {
    cancel: 'Cancel',
    save: 'Save',
    add: 'Add',
    remove: 'Remove',
    rename: 'Rename',
    delete: 'Delete',
    optional: 'Optional',
    archived: 'Archived',
    noValue: '—',
  },
  reorder: {
    handleFor: (name: string) => `Reorder ${name}`,
    roleDescription: 'reorderable item',
    instructions:
      'Press space or enter to pick up the item, the arrow keys to move it, space or enter to drop it, and escape to cancel. On a touch screen, press and hold the item, then drag it.',
    pickedUp: (name: string) => `Picked up ${name}.`,
    movedTo: (name: string, position: number, count: number) =>
      `${name} is at position ${position} of ${count}.`,
    droppedAt: (name: string, position: number, count: number) =>
      `${name} dropped at position ${position} of ${count}.`,
    cancelled: (name: string) => `Reordering cancelled. ${name} is back in its place.`,
  },
  tabBar: {
    label: 'Fitness tracker',
    home: 'Home',
    block: 'Current block',
    workout: 'Next workout',
  },
  navigation: {
    toHome: 'Fitness Tracker',
    toPrograms: 'Programs',
    toProgram: 'Program',
    toWorkout: 'Workout',
    toActiveProgram: 'Active program',
    toBlock: 'Current block',
    toExercises: 'Exercises',
  },
  notFound: {
    title: 'Not found',
    body: 'That page does not exist, or it is not yours.',
  },
  home: {
    title: 'Fitness Tracker',
    programsLink: 'Programs',
    exercisesLink: 'Exercises',
    weighIn: 'Weigh in',
    weighInInputLabel: 'Bodyweight in kg',
    lastEntry: (kg: string) => `Last entry: ${kg} kg`,
    currentProgram: (programName: string) => `Current program: ${programName}`,
    noActiveProgram: 'No active program',
    chooseProgram: 'Choose a program to start training.',
  },
  programs: {
    title: 'Programs',
    newProgram: 'New program',
    nameLabel: 'Name',
    blocksLabel: 'Blocks',
    create: 'Create',
    empty: 'No programs yet. Create one to start training.',
    summary: (blocks: number, workouts: number) =>
      `${blocks} ${blocks === 1 ? 'block' : 'blocks'} · ${workouts} ${workouts === 1 ? 'workout' : 'workouts'}`,
  },
  programEdit: {
    nameLabel: 'Program name',
    blocksTitle: 'Training blocks',
    blockLabelLabel: (blockNumber: number) => `Label for block ${blockNumber}`,
    addBlock: 'Add block',
    workoutsTitle: 'Workouts',
    addWorkout: 'Add workout',
    noWorkouts: 'No workouts yet. Tap + to add one.',
    activate: 'Activate',
    activateConfirmLabel: 'Activate and pause the other',
    activateWillPause: (otherName: string) => `${otherName} will be paused and keep its place.`,
    active: 'Active',
    pause: 'Pause program',
    openActiveProgram: 'Open the active program',
    futureOnlyNote: 'Changes apply to future workouts.',
    deleteProgram: 'Delete program',
    deleteConfirm:
      'Delete this program, its plan and its place in the program? Your logged sets are kept.',
    removeBlockFor: (blockNumber: number) => `Remove block ${blockNumber}`,
    removeBlockConfirmLabel: 'Remove block',
    removeBlockPlain: (blockNumber: number) => `Remove block ${blockNumber}?`,
    removeCurrentBlockMovesOn: (blockNumber: number, nextBlockNumber: number) =>
      `Block ${blockNumber} is the current block. Removing it moves you on to block ${nextBlockNumber}.`,
    removeCurrentBlockStartsAgain: (blockNumber: number) =>
      `Block ${blockNumber} is the current and last block. Removing it starts the program again at block 1.`,
    removeWorkoutFor: (name: string) => `Remove ${name}`,
    removeWorkoutConfirmLabel: 'Remove workout',
    removeWorkoutPlain: (name: string) => `Remove ${name}?`,
    removeWorkoutInProgress: 'Its open workout will be finished and its logged sets kept.',
    removeWorkoutMovesOn:
      'Removing it moves you on to the next unfinished workout, or the next block.',
  },
  workoutEdit: {
    nameLabel: 'Workout name',
    newTitle: 'New workout',
    create: 'Create workout',
    nameFirst: 'Name the workout, then add its exercises.',
    slotsTitle: 'Exercises',
    noSlots: 'No exercises yet. Add the first one.',
    addExercise: 'Add exercise',
    choose: 'Choose an exercise…',
    exerciseLabel: 'Exercise',
    newExerciseOption: 'New exercise…',
    newExerciseNameLabel: 'New exercise name',
    setsLabel: 'Sets',
    repsLabel: 'Reps',
    save: 'Save',
    removeSlotFor: (name: string) => `Remove ${name}`,
    removeSlotConfirmLabel: 'Remove exercise',
    removeSlotConfirm: (name: string) => `Remove ${name} from this workout?`,
    summary: (parts: string) => parts,
  },
  slotEdit: {
    exerciseTitle: 'Exercise',
    replace: 'Replace',
    replaceConfirmLabel: 'Replace exercise',
    replaceConfirm: 'Last weights for this exercise in this workout will be cleared.',
    replacementLabel: 'Replacement exercise',
    optionalToggle: 'Optional exercise',
    blockTitle: (blockNumber: number, label: string | null) =>
      label === null ? `Block ${blockNumber}` : `Block ${blockNumber} · ${label}`,
    setNumber: (setNumber: number) => `Set ${setNumber}`,
    targetRepsLabel: (setNumber: number) => `Reps for set ${setNumber}`,
    lastWeight: (kg: string) => `Last weight: ${kg} kg`,
    addSet: 'Add set',
    removeLastSet: 'Remove last set',
    quickFill: 'Quick fill',
    quickFillSetsLabel: 'Sets',
    quickFillRepsLabel: 'Reps',
    quickFillApply: 'Fill',
    removeSetsConfirmLabel: 'Remove sets',
    removeSetsConfirm: 'This removes sets that have a last weight.',
    copyFromPrevious: 'Copy from previous block',
  },
  activeProgram: {
    open: 'Open',
    currentBlock: 'Current block',
    blocksTitle: 'Blocks',
    progress: (finished: number, total: number) => `${finished} / ${total} workouts`,
    status: {
      complete: 'Complete',
      current: 'Current',
      upcoming: 'Upcoming',
      skipped: 'Skipped',
    },
    editProgram: 'Edit program',
    skipToFor: (blockTitle: string) => `Skip to ${blockTitle}`,
    startAgainAtFor: (blockTitle: string) => `Start again at ${blockTitle}`,
    skipConfirmLabel: 'Skip',
    skipConfirmLater: (target: number, skippedFrom: number, skippedTo: number) =>
      skippedFrom === skippedTo
        ? `Skip to block ${target}? Block ${skippedFrom} will be marked as skipped. Your logged sets are kept.`
        : `Skip to block ${target}? Blocks ${skippedFrom}–${skippedTo} will be marked as skipped. Your logged sets are kept.`,
    skipConfirmStartAgain: 'Start the program again from block 1? Your logged sets are kept.',
    skipOpenWorkout: 'Your open workout will be finished.',
    pause: 'Pause program',
    pauseConfirmLabel: 'Pause',
    pauseConfirm: 'Pause this program? It keeps its place.',
  },
  block: {
    name: (blockNumber: number) => `Block ${blockNumber}`,
    title: (blockNumber: number, label: string | null) =>
      label === null ? `Block ${blockNumber}` : `Block ${blockNumber} · ${label}`,
    blockComplete: (blockNumber: number) => `Block ${blockNumber} complete`,
    programComplete: 'Program complete, starting again at block 1',
    suggested: 'Up next',
    upNext: (workoutName: string) => `Up next: ${workoutName}`,
    finishedOn: (date: string) => `Finished ${date}`,
    inProgress: 'In progress',
    notStarted: 'Not started',
    noWorkouts: 'This program has no workouts.',
  },
  session: {
    heading: (workoutName: string, blockNumber: number | null) =>
      blockNumber === null ? workoutName : `${workoutName} · Block ${blockNumber}`,
    weightLabel: (setNumber: number, exerciseName?: string) =>
      exerciseName === undefined
        ? `Weight, set ${setNumber}`
        : `Weight, set ${setNumber}, ${exerciseName}`,
    repsLabel: (setNumber: number, exerciseName?: string) =>
      exerciseName === undefined
        ? `Reps, set ${setNumber}`
        : `Reps, set ${setNumber}, ${exerciseName}`,
    logLabel: (setNumber: number, exerciseName?: string) =>
      exerciseName === undefined
        ? `Log, set ${setNumber}`
        : `Log, set ${setNumber}, ${exerciseName}`,
    loggedLabel: (setNumber: number) => `Set ${setNumber} logged`,
    logSymbol: '✓',
    columns: { set: 'Set', weight: 'Weight (kg)', reps: 'Reps', log: 'Log' },
    finishWorkout: 'Finish workout',
    finishEmptyConfirmLabel: 'Finish',
    finishEmptyConfirm: 'Finish without logging any sets?',
    nothingToLog: 'There is nothing to log in this workout.',
  },
  exercises: {
    title: 'Exercises',
    nameLabel: 'New exercise name',
    add: 'Add exercise',
    filterLabel: 'Filter exercises',
    showArchived: 'Show archived',
    empty: 'No exercises yet. Add the first one.',
    noMatches: 'No exercises match.',
  },
  exerciseEdit: {
    nameLabel: 'Exercise name',
    usedIn: 'Used in',
    notUsed: 'Not used in any workout yet.',
    usedItem: (programName: string, workoutName: string) => `${programName} · ${workoutName}`,
    archive: 'Archive',
    unarchive: 'Unarchive',
    delete: 'Delete exercise',
    deleteConfirmLabel: 'Delete',
    deleteConfirm: 'Delete this exercise?',
  },
} as const;

export const fitnessErrorStrings: Record<FitnessErrorCode, string> = {
  unauthorized: 'Your session has ended. Sign in again.',
  unexpected: 'Something went wrong. Try again.',
  'not-found': 'That could not be found.',
  'invalid-body': 'That request was not understood. Try again.',
  'name-required': 'Enter a name.',
  'name-too-long': 'That name is too long.',
  'name-taken': 'That name is already used.',
  'invalid-weight': 'Enter a weight in kg with at most two decimals.',
  'invalid-reps': 'Reps must be a whole number from 1 to 999.',
  'invalid-target': 'Reps must be a whole number from 1 to 999.',
  'invalid-block-count': 'Enter a whole number of blocks, at least 1.',
  'invalid-time-zone': 'Your time zone could not be read.',
  'invalid-position': 'That position does not exist.',
  'invalid-block': 'That block cannot be chosen.',
  'prescription-needs-a-set': 'Every exercise needs at least one set.',
  'already-weighed-in-today': "You've already weighed in today.",
  'exercise-in-use':
    'This exercise is used in a workout or has logged sets, so it cannot be deleted. Archive it instead.',
  'exercise-archived': 'That exercise is archived. Unarchive it first.',
  'exercise-already-in-workout': 'This workout already has that exercise.',
  'program-active': 'Pause the program before deleting it.',
  'program-needs-a-block': 'A program needs at least one block.',
  'program-incomplete':
    'Add at least one workout, and a set for every exercise, before activating.',
  'no-active-program': 'There is no active program.',
  'workout-not-in-active-program': 'That workout is not part of the active program.',
  'workout-already-finished': 'That workout is already finished in this block.',
  'session-not-in-progress': 'That workout is already finished. The page has been refreshed.',
  'planned-set-not-in-session': 'That set is not part of this workout.',
  'set-already-logged': 'That set is already logged. The page has been refreshed.',
};
